#!/bin/sh

source "/lib/gentoo/functions.sh"
source "/etc/portage/make.conf"

pushd /usr/src/linux > /dev/null
K_VER="$(pwd -P | cut -f 2- -d '-')"
einfo "Kernel version is $K_VER"

einfo "Compiling kernel... ($MAKEOPTS)"
make $MAKEOPTS > /dev/null

einfo "Installing kernel..."
make modules_install install

einfo "Rebuilding out-of-tree kernel modules..."
emerge -1v @module-rebuild

# einfo "Creating initramfs..."
# dracut -Hf --kver $K_VER

einfo "Removing old kernels..."
rm /boot/*.old

einfo "Done"
popd
